# Generated by Django 6.0.5 on 2026-08-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_preset',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cartoon Avatar Preset'),
        ),
    ]
