# Generated by Django 6.0.5 on 2026-08-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_referral_profile_badge_profile_invite_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_temporary_name',
            field=models.BooleanField(default=True, help_text='True if using auto-generated User {number}', verbose_name='Temporary Display Name'),
        ),
    ]
