# Generated by Django 6.0.5 on 2026-08-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_is_temporary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP Address'),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='last_resend_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Resend Timestamp'),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='resend_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Resend Count'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Used'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['identifier', 'created_at'], name='accounts_ot_identif_b74d56_idx'),
        ),
    ]
