# Generated by Django 6.0.5 on 2026-09-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otpverification_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otpverification',
            name='accounts_ot_identif_8cf730_idx',
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['identifier', 'purpose', 'is_used', '-created_at'], name='accounts_ot_identif_4c3614_idx'),
        ),
    ]
