# Generated by Django 6.0.5 on 2026-09-01 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secure_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('join_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('creator_temp_name', models.CharField(max_length=50)),
                ('creator_avatar_color', models.CharField(default='#6366f1', max_length=20)),
                ('duration_choice', models.CharField(choices=[('1h', '1 Hour'), ('24h', '24 Hours'), ('7d', '7 Days')], default='24h', max_length=10)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_full', models.BooleanField(default=False)),
                ('max_participants', models.PositiveSmallIntegerField(default=2)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_private_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Room',
                'verbose_name_plural': 'Private Rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateRoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('is_creator', models.BooleanField(default=False)),
                ('temp_name', models.CharField(max_length=50)),
                ('temp_avatar_color', models.CharField(default='#06b6d4', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='private_rooms.privateroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Room Participant',
                'verbose_name_plural': 'Private Room Participants',
            },
        ),
        migrations.CreateModel(
            name='PrivateRoomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_msg_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('content', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Audio'), ('system', 'System')], default='text', max_length=15)),
                ('file', models.FileField(blank=True, null=True, upload_to='private_rooms/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_mime_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='private_rooms.privateroom')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='private_rooms.privateroomparticipant')),
            ],
            options={
                'verbose_name': 'Private Room Message',
                'verbose_name_plural': 'Private Room Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='privateroomparticipant',
            index=models.Index(fields=['room', 'session_key'], name='private_roo_room_id_19e2af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='privateroomparticipant',
            unique_together={('room', 'session_key')},
        ),
        migrations.AddIndex(
            model_name='privateroommessage',
            index=models.Index(fields=['room', 'created_at'], name='private_roo_room_id_d2f602_idx'),
        ),
        migrations.AddIndex(
            model_name='privateroommessage',
            index=models.Index(fields=['client_msg_id'], name='private_roo_client__0e581f_idx'),
        ),
    ]
