# Generated by Django 6.0.5 on 2026-09-01 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='privateroomparticipant',
            name='private_roo_room_id_19e2af_idx',
        ),
        migrations.RenameField(
            model_name='privateroomparticipant',
            old_name='session_key',
            new_name='session_token_hash',
        ),
        migrations.AddField(
            model_name='privateroom',
            name='is_blocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterUniqueTogether(
            name='privateroomparticipant',
            unique_together={('room', 'session_token_hash')},
        ),
        migrations.AddIndex(
            model_name='privateroomparticipant',
            index=models.Index(fields=['room', 'session_token_hash'], name='private_roo_room_id_97daa2_idx'),
        ),
    ]
