# Generated by Django 6.0.5 on 2026-09-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_rooms', '0002_remove_privateroomparticipant_private_roo_room_id_19e2af_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateroommessage',
            name='encrypted_file_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='privateroommessage',
            name='file_iv',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='privateroomparticipant',
            name='public_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
