# Generated by Django 6.0.5 on 2026-09-05 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_rooms', '0003_privateroommessage_encrypted_file_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='privateroom',
            index=models.Index(fields=['join_code', 'is_deleted', 'is_blocked', 'expires_at'], name='private_roo_join_co_7186e3_idx'),
        ),
        migrations.AddIndex(
            model_name='privateroom',
            index=models.Index(fields=['secure_token', 'is_deleted', 'is_blocked'], name='private_roo_secure__8d38b1_idx'),
        ),
    ]
