# Generated by Django 6.0.5 on 2026-09-05 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_rooms', '0004_privateroom_private_roo_join_co_7186e3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='privateroom',
            name='private_roo_join_co_7186e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='privateroom',
            name='private_roo_secure__8d38b1_idx',
        ),
        migrations.AddIndex(
            model_name='privateroom',
            index=models.Index(fields=['is_deleted', 'expires_at'], name='private_roo_is_dele_9c4b8d_idx'),
        ),
    ]
