# Generated by Django 6.0.5 on 2026-08-20 02:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('preferred_language', models.CharField(default='any', max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('matched', 'Matched'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=15)),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_queue_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match Queue Entry',
                'verbose_name_plural': 'Match Queue Entries',
                'indexes': [models.Index(fields=['status', 'queued_at'], name='matching_ma_status_6e534a_idx')],
            },
        ),
    ]
