# Generated by Django 6.0.5 on 2026-08-20 02:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='Room Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('topic', models.CharField(blank=True, max_length=50, verbose_name='Topic / Category')),
                ('description', models.TextField(blank=True, max_length=400, verbose_name='Description')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='room_avatars/%Y/%m/', verbose_name='Room Icon')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Room')),
                ('max_members', models.PositiveIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=15)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Member',
                'verbose_name_plural': 'Room Members',
                'indexes': [models.Index(fields=['room', 'user'], name='rooms_roomm_room_id_14fae5_idx')],
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_msg_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('content', models.TextField()),
                ('message_type', models.CharField(default='text', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rooms.room')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Message',
                'verbose_name_plural': 'Room Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['room', 'created_at'], name='rooms_roomm_room_id_2cafa6_idx')],
            },
        ),
    ]
