# Generated by Django 6.0.5 on 2026-09-05 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_enforce_unique_direct_pair_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['message', 'user', 'status'], name='chat_messag_message_c7b420_idx'),
        ),
    ]
